# ~/.bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# ---- History settings ----
HISTCONTROL=ignoreboth      # ignore duplicate lines and lines starting with space
HISTSIZE=5000
HISTFILESIZE=10000
shopt -s histappend         # append to history file, don't overwrite
shopt -s checkwinsize       # update LINES/COLUMNS after each command

# ---- Better cd behavior ----
shopt -s autocd             # type a directory name to cd into it
shopt -s cdspell            # autocorrect minor typos in cd

# ---- Prompt ----
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    color_prompt=yes
fi

if [ "$color_prompt" = yes ]; then
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='\u@\h:\w\$ '
fi
unset color_prompt

# ---- Colored output for common commands ----
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ---- Handy aliases ----
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h'
alias mkdir='mkdir -p'

# Safety nets
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Git shortcuts
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

# ---- Enable programmable completion ----
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# ---- Environment / PATH additions ----
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi

# ---- Editor ----
export EDITOR=vim   # or vim, or code --wait

# ---- Load machine-specific extras if present ----
if [ -f ~/.bashrc.local ]; then
    . ~/.bashrc.local
fi