#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022
# if running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private .local bin if it exists
if [ -d "$HOME/.local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

# load Work profile
if [ -d "/mnt/c/Users" ]; then
  echo 'I am at work'
  source "$HOME/.work-profile"
else
  echo 'I am not at work!'
fi

# Make cat == batcat (pretty cat)
# relies on batcat being installed (Ubuntu)
# Save the original system `cat` under `rcat`
alias rcat='$(which cat)'
# For Ubuntu and Debian-based `bat` packages
# the `bat` program is named `batcat` on these systems
alias cat='$(which batcat)'
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
export MANROFFOPT="-c"

# alias for fd
alias fd=fdfind

alias mk='$(which minikube)'

# Docker alias
alias docker-stop='docker stop "$(docker ps -q)"'
alias ds=docker-stop

# This setting makes OTHER_WRITABLE directories bold (1) and red (31)
# This is to override the default horrible colours
# Mostly to make working with Windows directories via WSL shells nicer
# LS_COLORS=$LS_COLORS':ow=1;31:'

export EDITOR=vim
export GIT_EDITOR=vim
# make grep results RED
export GREP_OPTIONS='--color=auto' GREP_COLOR='mt=1;32'

# set up eza aliases
source ~/dotfiles/eza/eza-config
