#!/bin/bash

# Java related bits
export JAVA_8=/usr/lib/jvm/java-8-openjdk-amd64
export JAVA_11=/usr/lib/jvm/java-11-openjdk-amd64
export JAVA_17=/usr/lib/jvm/java-17-openjdk-amd64
export JAVA_21=/usr/lib/jvm/java-21-openjdk-amd64

export JAVA_HOME=$JAVA_21
export STUDIO_JDK=$JAVA_21
export JDK_HOME=$JAVA_21
export PATH=$JAVA_HOME/bin:$PATH

# Following https://medium.com/@vpriyanshu671/how-to-install-apache-maven-of-version-3-9-8-on-ubuntu-d47cf536db04
export MAVEN_HOME=/opt/maven
export M2_HOME=/opt/maven
PATH=${MAVEN_HOME}/bin:$PATH

export DOTS=~/dotfiles

export WINHOME=/mnt/c/Users/mhr39349

export PROG=/mnt/c/programming
export BUSAPPS=$PROG/isisbusapps
export SITES=$PROG/SISites
export USERS=$PROG/Users
export MESSAGES=$PROG/Messages
export STAFFDETAILS=$PROG/StaffDetails
export FBS=/mnt/c/fbs/Apps

alias dots='cd $DOTS'
alias winhome='cd $WINHOME'
alias prog='cd $PROG'
alias busapps='cd $BUSAPPS'
alias ba='cd $BUSAPPS'
alias si='cd $SITES'
alias users='cd $USERS'
alias messages='cd $MESSAGES'
alias staffdetails='cd $STAFFDETAILS'
alias fbs='cd $FBS'

# Docker clean dangling images <none>:<none>
# from https://projectatomic.io/blog/2015/07/what-are-docker-none-none-images/
function docker-clean() {
  docker rmi $(docker images -f "dangling=true" -q)
}

# Stop all running containers
function docker-stop-all() {
  docker stop $(docker ps -q)
}

alias dsa='docker-stop-all'

export DOCKER_BUILDKIT=1

# k8s config - dev
export KUBECONFIG_DEV="$HOME/.kubecfg/dev/dev-v3.kubeconfig"
export KUBECONFIG_DEV_FALLBACK="$HOME/.kubecfg/dev/kubefallback.kubeconfig"
export KUBECONFIG_DEV_MAN="$HOME/.kubecfg/dev/management-v3.kubeconfig"
export KUBECONFIG_DEV_LOADTEST="$HOME/.kubecfg/dev/load-testing-v3.kubeconfig"

# k8s config - prod
export KUBECONFIG_PROD="$HOME/.kubecfg/prod/prod-v4.kubeconfig"
export KUBECONFIG_PROD_FALLBACK="$HOME/.kubecfg/prod/prod-fallback.kubeconfig"
export KUBECONFIG_PROD_MAN="$HOME/.kubecfg/prod/management-prod-v3.kubeconfig"

# k8s config - Infra
export KUBECONFIG_INFRA="$HOME/.kubecfg/infra/infra-v2.kubeconfig"

# DEFAULT - CONNECT TO DEV
export KUBECONFIG=$KUBECONFIG_DEV

function switch-k8s() {
  if [ $1 = 'd' ]; then
    export KUBECONFIG=$KUBECONFIG_DEV
    echo "Switch to k8s dev: $KUBECONFIG"
  elif [ $1 = 'p' ]; then
    export KUBECONFIG=$KUBECONFIG_PROD
    echo "Switch to k8s prod: $KUBECONFIG"
  else
    echo "Didn't understand chose, k8s is still $KUBECONFIG"
  fi
}

alias sk='switch-k8s'

alias fbs='cd $FBS'

# Just checking
echo "Loaded shodders work profile"
echo "Using kubeconf: $KUBECONFIG \n\n"

# Set some envs to use with docker (bypassing fba-compose)
export FBA_COMPOSE_DIR=${FBA_COMPOSE_DIR:-/mnt/c/programming/docker-orchestration}
export WINDOWS_HOST=$(ip route show | grep -i default | awk '{ print $3 }')
export REPOS_ROOT_DIR=${REPOS_ROOT_DIR:-~/repos}
export WIN_REPOS_ROOT_DIR=${WIN_REPOS_ROOT_DIR:-/mnt/c/programming}
export WIN_USER_DIR=$(wslpath "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null | tr -d '\r')")

# shortcut for running docker compose with correct compose/env files
alias lc='docker compose -f $FBA_COMPOSE_DIR/docker-compose.yml --env-file $FBA_COMPOSE_DIR/.env'

# If using NVM for node version management
# Follow this: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
